{% set name = "morecantile" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fd814f43466306e576b43902df8400dcf5308a30c88c54822a42e9d32376d21

build:
  number: 0
  noarch: python
  entry_points:
    - morecantile=morecantile.scripts.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - attrs
    - click
    - pydantic
    - pyproj ~=3.1
    - rasterio >=1.2.1

test:
  imports:
    - morecantile
    - morecantile.data
    - morecantile.scripts.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/morecantile
  summary: Construct and use map tile grids (a.k.a TileMatrixSet / TMS).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - ocefpaf
