{% set name = "morecantile" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 374d636a74346e9b5ca5f64a36f3bad88a3177def42e782cda4e66816369de37

build:
  number: 0
  noarch: python
  entry_points:
    - morecantile=morecantile.scripts.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - pydantic
    - python >=3.0
    - rasterio >=1.1.7

test:
  imports:
    - morecantile
    - morecantile.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/morecantile
  summary: Construct and use map tile grids (a.k.a TileMatrixSet / TMS).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
