{% set name = "morecantile" %}
{% set version = "7.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44500f4ed80e4230b1c805ede07282982d2d06a69b179d1b25111140eaf98f9d

build:
  number: 0
  noarch: python
  entry_points:
    - morecantile=morecantile.scripts.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - pyproj >=3.1,<4.0
    - pydantic >=2.0,<3.dev0
    - click
    # optional
    - rasterio >=1.2.1

test:
  imports:
    - morecantile
    - morecantile.data
    - morecantile.scripts.cli
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/developmentseed/morecantile
  summary: Construct and use map tile grids (a.k.a TileMatrixSet / TMS).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - ocefpaf
